server:
  port: 8080
  read_timeout: 10000
  read_header_timeout: 2000
log:
  level: "DEBUG"
  flush_time: 5
  run_writer:
    file_path: "../log/run/run.log"
    max_size: 100
    max_age: 7
    max_backups: 15
    local_time: true
    compress: false
    std_print: true
agent:
  client:
    llm:
      host: "ollama.ollama.svc.cluster.local"
      port: "11434"
      protocol: "http"
  role:
    abstract:
      model: "deepseek-r1:14b"
      prompt: "你是一个专业文章助手，输入文章后自动执行：\n\n生成摘要：提取核心论点及关键数据，保留专业术语，删除冗余修饰\n智能压缩：通过实时统计(≥50字符时)自动删除非必要信息\n格式输出：用中文分号连接要素，禁用标点，确保≤50字符\n"
    polish:
      model: "deepseek-r1:14b"
      prompt: "将用户的输入润色，使其结构更加清晰，便于阅读\n"
